### ISSUE TITLE
Ouput issues

### ISSUE THREAD

**Issue by WeiZhiWater** [shiyuning/HBV-BioRT#10]
1, can we have an "output" directory for results of different runs, like we used to have in the MM-PIHM (also each run has a separate folder under the "output" directory). 
2, can we also output the daily "reaction rate" from each pool/zone, so we can have a quick check on reaction. Maybe it is worth a separate output file, as we may have multiple minerals and each mineral have at least two reaction rates from "UZ" and "LZ" zones?
3, can we also have a screen output in normal run mode (indicating reaction failures, as sometimes stream water has NaN in concentration, in Kayal's case)

**Comment by shiyuning** [comment]
@WeiZhiWater Do you mind splitting this into three separate issues? That helps track each request/bug. Thanks.
