### ISSUE TITLE
Add output of reaction rate

### ISSUE THREAD

**Issue by WeiZhiWater** [shiyuning/HBV-BioRT#12]
Can we also output the daily "reaction rate" from each pool/zone, so we can have a quick check on reaction? Maybe it is worth a separate output file, as we may have multiple minerals and each mineral have at least two reaction rates from "UZ" and "LZ" zones?

**Comment by shiyuning** [comment]
What do you mean by reaction rate? Change of concentration of each species caused by reaction?

**Comment by WeiZhiWater** [comment]
> What do you mean by reaction rate? Change of concentration of each species caused by reaction?

yes, specifically, I guess daily "reaction rate" [mol/d] could make more sense. Not the rate constant k, but the actual daily reaction rate under the effects of soil moisture and temperature.

**Comment by WeiZhiWater** [comment]
Hi, Yuning:

Just use the following equation to calculate the daily reaction rate: let's for *C_t* is the mineral concentration [mol/L-poroous medium] at the time of t day.

So the reaction rate is for the t day is: (*C_t* - *C_t-1*) [mol/L-poroous medium] * V [m3] * porosity [m3/m3] * 1000

**Comment by shiyuning** [comment]
@WeiZhiWater What *V* should we use? So reaction rate is not per unit volume?

**Comment by WeiZhiWater** [comment]
That's a good question. I tended to look at the whole watershed reaction rate (not comparing reaction rate in each grid). It is more useful when we are expecting the changed reaction rate by changing its rate constant, soil moisture/temperature function, or just quantifying the contribution of reaction rate by each zone (shallow GW, deep GW). So I think the whole reaction rate over the unit (or sub-catchment) is more useful? So V probably should be the total volume of each zone (shallow GW, deep GW) over the unit (or sub-catchment). What do you think?

**Comment by WeiZhiWater** [comment]
Or is it the catchment (or sub-catchment) are not defined in the HBV?

**Comment by shiyuning** [comment]
@WeiZhiWater It is not being used when you have only one sub-catchment. Everything is depth based.

**Comment by WeiZhiWater** [comment]
Then perhaps we have to use the depth and output reaction rate in the unit of mol/m2/d. I think we can use this.

**Comment by shiyuning** [comment]
Should I use total concentration or primary concentration?

**Comment by WeiZhiWater** [comment]
I think we should target the solid phase for outputting their reaction rates. That means, to use the total concentration since the solid-phase won't have speciation (total concentration should be equal to primary concentration).

**Comment by shiyuning** [comment]
Thanks, @WeiZhiWater . I am not sure what the purpose of the printed reaction rate is. If it is to check if the change of concentration is OK, shouldn't we just use mol/L/d? Perhaps I didn't understand this correctly.

**Comment by WeiZhiWater** [comment]
I think it is easier to do a self-check. For example, 1) check the mass balance of chemical reaction, the released chemicals from solid-phase vs. discharged and stored mass in streamflow and soil/gw water; 2) I guess would be easier to track how reaction and environmental conditions works, for example, is reaction happening as I would expect. For example, a double rate constant is expected to release 2x more solutes into water phase, but the concentration may not be doubled (due to water storage changes). But from the reaction output, at least, we know the system (reaction) is working properly, just need to check on other factors.
