### ISSUE TITLE
Reaction Stoichiometry not reflected in output

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#14]
In simulation, I used Dolomite that dissolves to give 1.45 Ca and 0.55 Mg per mole of dolomite, but in output the concentration of Ca and Mg are equal at time steps after few days. The stoichiometry in the display while running the model is correct.

**Comment by KayalvizhiSadayappan** [comment]
I just now saw something in display. No kinetic reaction is being read. This is potentially the problem. But I don't think there is anything wrong in the input file. I will send you the input files and output. 
![dolomite_screen](https://user-images.githubusercontent.com/70716152/109670558-39ef3200-7b41-11eb-967d-83927f8e6d62.png)

**Comment by shiyuning** [comment]
You can directly attach your input files with the issues. That is much easier for me to match issues with input files.

**Comment by KayalvizhiSadayappan** [comment]
I have attached them here.
[konza_dol.zip](https://github.com/shiyuning/HBV-BioRT/files/6070822/konza_dol.zip)
[konza_dol_results.txt](https://github.com/shiyuning/HBV-BioRT/files/6070823/konza_dol_results.txt)

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan The issue is caused by the lack of newline character at the end of the file. I don't know how to fix this. Did you edit this file in Windows and then uploaded it?

**Comment by KayalvizhiSadayappan** [comment]
I didn't edit in windows. After seeing your message, I tried it running
after pressing enter at the end of mineral reaction and saving the file. It
worked. Thanks!

**Comment by shiyuning** [comment]
I actually fixed this. You can try it by using your old input file.
What text editor did you use to generate the file? I want to look it up and see what is causing the problem.

**Comment by KayalvizhiSadayappan** [comment]
I am using 'portal.aci.ics.psu.edu' to edit all files on the cluster. Not
sure what editor it is. I have attached pictures of chem file in the text
editor when it didn't work and when it worked. Maybe that will help?
