### ISSUE TITLE
Inhibition term not used in code

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#15]
In react.c, inhibition term 'inhinterm' is calculated but not used anywhere to modify the reaction rate. Can you check that? Thanks!

**Comment by shiyuning** [comment]
You are right, it is not being used.

I did not code the reaction part so @WeiZhiWater will need to take a look and fix this.

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan I checked Wei's BioRT code and inhibterm does not do anything. We can discuss tomorrow.

**Comment by shiyuning** [comment]
`inhibterm` should be multiplied to `monodterm`.
