### ISSUE TITLE
Installation error in lastest version

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#17]
**Describe the bug**
Error occurs while installing cvode

**To Reproduce**
version uploaded after fix for newline character
![Error_message](https://user-images.githubusercontent.com/70716152/109812930-ad08af00-7bfa-11eb-9d07-d4d7807e3dcb.png)

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan I checked installing on both MacOS and Unix and found no problem. Can you try again?
