### ISSUE TITLE
Secondary Species concentration 

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#2]
I simulated chloride transport alone with Cl- ,H+ and OH-. The results indicate that OH- is always 10^-20,  but it should be around 10^-9. Are all values below a certain threshold displayed as 1E-20? In bioRT-Flux-PIHM, only minerals are printed as 1E-20. That's why I wanted to ask this.

**Comment by shiyuning** [comment]
Are you running it using the transport only mode? When simulating transport, only aqueous species are considered, without reactions or speciation. So secondary species are not updated. Should we do speciation?

**Comment by KayalvizhiSadayappan** [comment]
Yes, I was running on transport mode. What you say makes sense. If I were to use only Cl- or some other non reactive tracer, it doesn't matter if there is no speciation. But if H+ is involved, I feel OH- should be calculated according to speciation even if transport alone is simulated. Let's consult Lili on it.
