### ISSUE TITLE
Species concentration in river drops to zero when the flow is almost zero but still not zero and therefore should have concentration same to SLZ

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#4]
In results, I observed that the species concentration in river drops to zero, when the flow is zero which is fine. But at some time steps, there is very small flow in stream but Cl concentration is zero (though SLZ still has high Cl concentration) . Since there is even slight flow, it should be from SLZ, therefore should have same Cl concentration as the SLZ. 

P.S: On transport mode

**Comment by shiyuning** [comment]
Can you share with me the input you used and let me know on which day did you see it?

**Comment by KayalvizhiSadayappan** [comment]
I have sent you the files on Slack. It seems like a problem caused by precision. Qsim has 9 decimal places while Q2 only has 3 decimal places. So calculations done based on Q2 causes problem.

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan Then we will not be able to fix this. We don't know if Qsim comes from Q2, or Q1 and Q2.
