### ISSUE TITLE
Discrepancy between initial conditions considered in model vs given initial conditions in cini file?

### ISSUE THREAD

**Issue by KayalvizhiSadayappan** [shiyuning/HBV-BioRT#6]
The infiltration concentration is set as concentration of upper zone (in cini file) for the first day in the model. Wouldn't it make more sense to be rainfall concentration? Also upper and lower zone concentrations start at a value different from the given input concentrations

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan Considering long term equilibrium, infiltration concentration would be closer to the shallow zone than to precipitation. Thus we start the infiltration rate with upper zone concentration.

**Comment by shiyuning** [comment]
> Also upper and lower zone concentrations start at a value different from the given input concentrations

Can you elaborate on this? In what mode and for what species do you see the discrepancy?

**Comment by KayalvizhiSadayappan** [comment]
HCO3- concentration in Upper zone was given as 2.93E-4 while the first day HCO3- concentration in upper zone is 9.563E-5. What process is causing such a difference? 
![cini_output](https://user-images.githubusercontent.com/70716152/109433687-a94d1080-79df-11eb-8f02-9e7508eab393.png)

**Comment by shiyuning** [comment]
@KayalvizhiSadayappan That is caused by reaction.
