### ISSUE TITLE
Add Q10 function 

### ISSUE THREAD

**Issue by WeiZhiWater** [shiyuning/HBV-BioRT#7]
Could we have the Q10 function in the rate law, for now, we could read the air "temperature" from "Results.txt".

**Comment by shiyuning** [comment]
Last time we discussed, Lili said to drop temperature control. Let's discuss on Wednesday.

**Comment by WeiZhiWater** [comment]
> Last time we discussed, Lili said to drop temperature control. Let's discuss on Wednesday.

o ~ I guess she changed her mind today and said we can use air temperature for now. Better to keep all functions there.
