### ISSUE TITLE
Add soil mositure function in the Monod rate law

### ISSUE THREAD

**Issue by WeiZhiWater** [shiyuning/HBV-BioRT#8]
We already have these two parameters of "SW_THRESHOLD" and "SW_EXP", can we add the latest soil moisture function to the Monod rate law. Thanks, Yuning.

**Comment by shiyuning** [comment]
Is this what you requested? It is already in the code: https://github.com/shiyuning/HBV-BioRT/blob/ef3ba9d51ed9d0cc626bcab7d364b00f6a4c149c/src/react.c#L78-L87

Let me know if this is not.

**Comment by WeiZhiWater** [comment]
> Is this what you requested? It is already in the code:
> 
> https://github.com/shiyuning/HBV-BioRT/blob/ef3ba9d51ed9d0cc626bcab7d364b00f6a4c149c/src/react.c#L78-L87
> 
> Let me know if this is not.

I forgot it is coded into the "area" term. Thanks.
